# Additional services for API documentation

version: '3.8'

services:
  # Swagger UI standalone service (optional)
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: apate-swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON_URL=http://localhost:8000/openapi.json
      - BASE_URL=/swagger-ui
      - DEEP_LINKING=true
      - DISPLAY_OPERATION_ID=true
      - DEFAULT_MODELS_EXPAND_DEPTH=2
      - DEFAULT_MODEL_EXPAND_DEPTH=2
      - DISPLAY_REQUEST_DURATION=true
      - DOC_EXPANSION=list
      - FILTER=true
      - SHOW_EXTENSIONS=true
      - SHOW_COMMON_EXTENSIONS=true
      - TRY_IT_OUT_ENABLED=true
    depends_on:
      - apate-api
    networks:
      - apate-network
    restart: unless-stopped
    labels:
      - "com.apate.service=documentation"
      - "com.apate.environment=development"

  # ReDoc standalone service (optional)
  redoc:
    image: redocly/redoc:latest
    container_name: apate-redoc
    ports:
      - "8081:80"
    environment:
      - SPEC_URL=http://localhost:8000/openapi.json
      - PAGE_TITLE=Apate Honeypot API Documentation
      - PAGE_FAVICON=https://github.com/Rizzy1857/Apate/favicon.ico
    depends_on:
      - apate-api
    networks:
      - apate-network
    restart: unless-stopped
    labels:
      - "com.apate.service=documentation"
      - "com.apate.environment=development"

networks:
  apate-network:
    external: true